name: Update README with Date and Time

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  repository_dispatch:
    types: [uptime]
  workflow_dispatch:
  
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout the current repository
      - name: Set up Git for committing
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      - name: Get current date and time
        id: date-time
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
      - name: Update README.md
        run: |
          sed -i "s/Last updated: .*/Last updated: ${{ steps.date-time.outputs.date }}/" README.md
      - name: Commit changes
        run: |
          sed -i "s/Last updated: .*/Last updated: ${{ steps.date-time.outputs.date }}/" README.md
          git add README.md
          git commit -m "Update README with current date and time"
          git push
      - name: Push changes to the target repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          repository: ${{ env.REPO }}  # Access the repository from the REPO environment variable
          branch: main
